baseURL = '/'
languageCode = 'en-us'
title = 'Alexanders hemsida'

[taxonomies]
  tag = "tags"
  category = "categories"

sectionPagesMenu = "main"

paginate = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.tableOfContents]
    endlevel = 3
    ordered = false
    startLevel = 1