baseURL = '/'
languageCode = 'en-us'
title = 'Alexanders hemsida'
disableKinds = ["taxonomy","taxonomyTerm"]

sectionPagesMenu = "main"

paginate = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true